server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jw-springboot
    username: root
    password: 123456
  thymeleaf:
    cache: false
  banner:
    location: public/banner.txt
shiro:
  loginUrl: /
